### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by AndyObtiva** [AndyObtiva/glimmer_wordle#23]
Windows Support

**Comment by rubyFeedback** [comment]
Has there been any update in this regard?

I am currently extending java-specific code, including swing + jruby, so I will be busy with windows-specific things. (My current aim will be to try to write as much swing-specific code, use it primarily via jruby, to make windows more useable, so a bit like glimmer; but to also map down which widgets I need in the long run. And at a later point to see how much of this could be turned into glimmer + libui automatically. But I'd like to test as much things as possible on windows. On linux I don't have these problems but on windows I kind of need all the power of GUIs in the world.)

**Comment by AndyObtiva** [comment]
Windows is already supported because Glimmer Wordle is written with [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt), which runs on Windows. **But, the styling is not tweaked for Windows yet, and that's the only thing needed to be done for Windows**. It shouldn't be a tough job for anyone to tackle given that the game is completely implemented already.

And, why consider Swing when SWT is far superior and better?! [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) is the most advanced [Glimmer GUI](https://github.com/AndyObtiva/glimmer) library, and it renders OS native widgets, unlike Swing, which doesn't have native widgets and has freeze-up issues on some systems, especially older ones. If I were you, I'd use [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) without thinking twice. I'm not sure why you like to make bad decisions sometimes when the good decisions are right in front of you. You could be supporting me instead by using [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) extensively on all platforms and reporting any issues you encounter to me to fix and improve if any. [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) gives you the ability to [automatically package your app as a Window MSI/EXE](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_PACKAGING_AND_DISTRIBUTION.md) too, including Java WITHOUT requiring a separate installation step, which you can't do with Swing without doing a lot of extra work. [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) should always be the smart default go to option for Ruby GUI unless there is a strong reason not to use Java.

In any case, if you want to use Swing, it would be simpler to use it with Glimmer DSL for Swing (but I still recommend not spending time on anything but [Glimmer DSL for SWT](https://github.com/AndyObtiva/glimmer-dsl-swt) in JRuby):
https://github.com/AndyObtiva/glimmer-dsl-swing

**Comment by AndyObtiva** [comment]
Windows has been officially supported by tweaking the styling to look nice in it. This was done in version 1.1.5, which was just released to RubyGems:
https://rubygems.org/gems/glimmer_wordle/versions/1.1.5

![windows screenshot of wordle](https://raw.githubusercontent.com/AndyObtiva/glimmer_wordle/master/screenshots/glimmer-wordle-windows.png)

I am closing this issue as it is fully handled.
