### ISSUE TITLE
Show the correct word when all attempts have failed?

### ISSUE THREAD

**Issue by kojix2** [AndyObtiva/glimmer_wordle#3]
Hi!

I am not very good at English. All my English is written by Deepl or Google Translate. 
So I often can't get to the correct answer until the end. It would be nice if the correct word is shown when you fail.

![image](https://user-images.githubusercontent.com/5798442/154052635-f5e540df-dc17-4d07-b576-75ef078fd568.png)

**Comment by AndyObtiva** [comment]
Done! (in [v1.1.0](https://rubygems.org/gems/glimmer_wordle/versions/1.1.0))

In this example, the answer was SAUCY:
![Screen Shot 2022-02-27 at 7 36 24 PM](https://user-images.githubusercontent.com/23052/155907072-f1acfcc7-b0c4-49a2-bc8b-e30cf878d4d4.png)

**Comment by AndyObtiva** [comment]
@kojix2 Just a quick note that I added official support for Linux by improving the fonts/look and feel in [v1.1.3](https://github.com/AndyObtiva/glimmer_wordle/tree/v1.1.3)

![Linux screenshot](https://raw.githubusercontent.com/AndyObtiva/glimmer_wordle/master/screenshots/glimmer-wordle-linux.png)

Also, you should be able to [download as DEB or RPM on Linux](https://github.com/AndyObtiva/glimmer_wordle#download) now, or alternatively [use the Ruby gem](https://github.com/AndyObtiva/glimmer_wordle#install-ruby-gem) successfully (the gem had an issue before, but it's fixed now)

**Comment by kojix2** [comment]
Thanks for your reply
I installed the deb package of glimmer-wordle on Ubuntu.

Look at the dpkg -L command.

`dpkg -L glimmer-wordle`

I found that all files are installed in the /opt directory.
So GUI apps made with JRuby and glimmer-dsl-swt can be packaged like this.
